### ISSUE TITLE
Video entity page is not displaying correctly

### ISSUE THREAD

**Issue by sarabeckman** [denshoproject/ddr-public#146]
Published [ddr-densho-354-2125](http://ddr.densho.org/ddr-densho-354-2125/) today. The genre/format of the entity is motion picture/audio visual. The video file is external and hosted at IA. 

The page on the ddr shows the signature and then below the video is listed as a File. When you click on the file the video does stream for IA and the download from IA also works. 

See [this CSUJAD entity](http://ddr.densho.org/ddr-csujad-31-1/) for the correct way a motion picture/audio visual entity should be displayed.

**Comment by gjost** [comment]
Looks like there's missing object format data.  From the page HTML.  `templatekey` should be `av:video`.
```
<div id="object-display">
  | <!--
  | templatekey: av:
  | template:    ui/entities/detail.html
  | IA metadata: {'original': None, 'http_status': 200, 'mimetype': '', 'files': {}, 'xml_url': 'https://archive.org/download/ddr-densho-354-2125/ddr-densho-354-2125_files.xml', 'id': 'ddr-densho-354-2125'}
  | -->
```

The `mimetype` looks weird: `video/quicktime`.  I would expect `video/mp4`.
```
>>> from ui import models
>>> f = models._object(request=None, oid='ddr-densho-354-2125-mezzanine-be5c46fe64')
>>> for k,v in f.items():
...     k,v
... 
('id', 'ddr-densho-354-2125-mezzanine-be5c46fe64')
('model', 'file')
('title', 'Full Movie')
('access_rel', 'files/ddr-densho-354-2125/files/ddr-densho-354-2125-mezzanine-be5c46fe64-a.jpg')
('basename_orig', 'Kubota Final.MOV')
('mimetype', 'video/quicktime')
...
```

The `ia_meta` field in the API video of the object (http://ddr.densho.org/api/0.2/ddr-densho-354-2125/) is curiously empty.

Is Quicktime one of our accepted formats?

**Comment by gjost** [comment]
Currently the `ddr-cmdln` code lists the following supported media types for IA: mp3, mp4, mpg, ogv, png (source: https://github.com/densho/ddr-cmdln/blob/master/ddr/DDR/archivedotorg.py#L24).

Conclusion: bad mimetype?

**Comment by GeoffFroh** [comment]
@sarabeckman, @GeoffFroh and Caitlin need to have a conversation about the policy for video binaries.

**Comment by sarabeckman** [comment]
Decided that the mp4 derivative created my IA would be the mezzanine for the DDR. Today I imported the a new CSV with the information for the mp4 and then deleted the .MOV external file from the git repository. 

I then reindexed the collection. The display problem persisted and the .MOV file was still listed. @GeoffFroh manually deleted the .MOV file from ES index. He reviewed the file JSON for the mp4 file and fixed an error in the external url field. The collection was synced and the entity was reindexed. The .MOV file was gone, but the display issue persisted. 

I then preformed a reindex on the whole collection instead of the one entity and the display issue has still persisted. 

In the [raw json](https://ddr.densho.org/api/0.2/ddr-densho-354-2125/) the values for `template` is still `av:` even after reindex. 

**Next step** - Comparing `ddr-densho-354-2125` file json with file jsons from `ddr-csujad-31` that also has external video files.

**Comment by gjost** [comment]
IA is still listing the .MOV file as the original.  Is it possible to upload the file to IA again?  (For the life of me I can't remember right now how that happens).
```
...
<file name="ddr-densho-354-2125-mezzanine-be5c46fe64.MOV" source="original">
<mtime>1579888584</mtime>
<size>1448386287</size>
<md5>5546b61adeaf6ed6d34e492a11da18a2</md5>
<crc32>59b016c1</crc32>
<sha1>be5c46fe64df64a1f2879daddd5f6d8e0e3cf567</sha1>
<format>QuickTime</format>
<length>3016.78</length>
<height>486</height>
<width>720</width>
</file>
...
```
See https://ia801403.us.archive.org/21/items/ddr-densho-354-2125/ddr-densho-354-2125_files.xml

**Comment by GeoffFroh** [comment]
Fixed the data in the production site ES index itself. This defect will likely return if/when the collection is indexed again with the current version of `ddr-cmdln`. May need to revisit with a functionality enhancement to the indexer.

**Comment by GeoffFroh** [comment]
Corrected version of ddr-densho-354-2125 from ES index. 

[ddr-densho-354-2125-fixed.json.txt](https://github.com/denshoproject/ddr-public/files/4724533/ddr-densho-354-2125-fixed.json.txt)
