### ISSUE TITLE
favicon missing from assets

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/ddr-public#158]
Referenced at: https://github.com/denshoproject/ddr-public/blob/master/conf/nginx.conf#L20

Where did this image go? Used to exist; and will need to be injected into the static assets package.

**Comment by gjost** [comment]
I set up a new `ddr-public-assets` package like `encyc-rg-assets`, added a favicon to it, and added the proper links in `ddr-public` commits `d247cde` and `b9e78c9`.

I hope this will be a better way to distribute and install static files than our current setup.

**Comment by gjost** [comment]
It also occurs to me that we could install the `ddr-public-assets` package directly on `warhorse` and serve static files from there, saving a couple hops.
