### ISSUE TITLE
ui: segment-video template should not display IA binary download links if mezzanine content is not present at IA

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/ddr-public#163]
Some VH collections are marked "stream-only" due to licensing/usage agreements (e.g., ddr-densho-122). We have removed the higher quality originals (MPEG2 and OGV) from IA. In this case, we should only display a player and not have links to materials in IA. 

Currently, the segment-video template (https://github.com/denshoproject/ddr-public/blob/master/ddrpublic/ui/templates/ui/entities/segment-video.html#L89) assumes the content will always be present and displays  links to mp4 and mpg types regardless of whether they are available at IA. 

The application should assume that if `segment.ia_meta.files.mpg` does not exist, it should not display the mp4 and mpeg download buttons. The `segment-video.html` template (and the `entity-video.html` template?) could just contain a simple  `{% if %}` block that check for the var. 

QUESTION: Will this issue create a problem with indexing in https://github.com/denshoproject/ddr-cmdln? See: https://github.com/denshoproject/ddr-cmdln/issues/191

**Comment by gjost** [comment]
Fixed in `ddr-public` commit `adbcd5f` for next package.

**Comment by GeoffFroh** [comment]
Appears to have returned; see: https://ddr.densho.org/interviews/ddr-densho-122-10-1/

**Comment by GeoffFroh** [comment]
Likely a regression issue related to denshoproject/ddr-cmdln#199

This shows in video entities that are allowed for stream-only from IA. (ddr-densho-122)
