### ISSUE TITLE
ui: change JAMO (ONE) logo image on About page

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/ddr-public#164]
The JAMO (formerly known as ONE) logo has changed. It needs to be replaced on the About page

**Comment by GeoffFroh** [comment]
Fixed in eb8f70b9578d2d815e6f60ff2be687497c1751fe

@gjost: Please add to next package deployment

**Comment by gjost** [comment]
Merged into master, pulled on production, and restarted.
