### ISSUE TITLE
ui: Temporarily remove ddr-densho-122 VH download links

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/ddr-public#165]
Download links for both mpeg2 and mp4 content need to be removed from the `segment-video.html` template. This fix will be superseded by #163 after content is removed from IA. 

IMPORTANT: The streaming player should __not__  be removed. Just the download buttons.

**Comment by GeoffFroh** [comment]
@gjost: please merge to `master` and deploy ASAP

**Comment by gjost** [comment]
Merged the change into master, pulled in production, and restarted.  It's up.

**Comment by GeoffFroh** [comment]
Appears to have returned; see:
