### ISSUE TITLE
ui: "Download large" button on entity detail page downloads full-size image

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/ddr-public#172]
Clicking on the "Download large" button on the entity detail page triggers a download of the full-size tiff image, rather than the expected jpg access file. The link appears to be correct when the user hovers on the button, and right-click open works as expected, but the `download` attribute in the template is set incorrectly to the full-size file url. See example below from https://ddr.densho.org/ddr-densho-118-3/:

```
            <div id="object-download">
              <a href="https://ddr.densho.org/media/ddr-densho-118/ddr-densho-118-3-mezzanine-5f37cab05a-a.jpg" download="ddr-densho-118-3-mezzanine-5f37cab05a.tif" class="btn btn-default btn-xs">
                <i class="fa fa-download"></i>
                Download large
                (162.7 KB)
              </a>
              <a href="https://ddr.densho.org/media/ddr-densho-118/ddr-densho-118-3-mezzanine-5f37cab05a.tif" download="ddr-densho-118-3-mezzanine-5f37cab05a.tif" class="btn btn-default btn-xs">
                <i class="fa fa-download"></i>
                Download full-size
                (14.9 MB)
              </a>
```

**Comment by gjost** [comment]
Fixed(?) in `ddr-public` commit `edc53da` and pulled to ddrstage.  Please confirm.
