### ISSUE TITLE
Search does not return results for `creators:` links

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/ddr-public#181]
The "Creators" field in the entity detail pages contain links that trigger canned ES searches. However, none of these links return any results. it appears that the `creators` attribute is not being properly indexed. 

See for example:

https://ddr.densho.org/ddr-densho-37-186/
https://ddr.densho.org/ddr-densho-37-187/

The creator -- R.H. Ross -- has multiple photos so should return results, but the canned search does not return anything. 

Note that plain full-text searches for "Ross, R.H." or "Ross" also fail to return either one of the photos above. 

@sarabeckman: would you please check to see whether this behavior is also present for "Persons/Organizations" field?

**Comment by gjost** [comment]
It's possible the `creators` field is a non-indexed `Keyword` field instead of an indexed `Text` field.  The former is more for filtering while the latter is for free-text searching.  `creators` may have not gotten included in searchable fields lists for something.  I'll poke around in the code.

**Comment by sarabeckman** [comment]
It looks like the names listed in the "Persons/Organizations" field are not links to a canned ES search like the "creators" field.  See the links below for examples:

https://ddr.densho.org/ddr-densho-356-7/  
https://ddr.densho.org/ddr-densho-377-1/

**Comment by gjost** [comment]
Fixed creators and persons fields as of `ddr-public` commit `12f50ae` on the develop branch.  Commit has been pulled to ddrstage.

Note that this (re?)enables searches like the following, in which `creators:LASTNAME, FIRSTNAME` appears in the `fulltext` field of the URL:
https://ddrstage.densho.org/search/results/?fulltext=creators:Frost,%20Jack

`person` searches work the same way:
https://ddrstage.densho.org/search/results/?fulltext=persons:Yorita,%20Patsy

The `?fulltext=creators:NAME` thing is awkward but to change it would mean a light refactor of the ddrpublic search code.

**Comment by sarabeckman** [comment]
Tried both creator & person search on ddrstage with ddr-densho-425 and ddr-densho-426. Both work as expected.

**Comment by GeoffFroh** [comment]
@gjost: This should be ready to merge to `master`, package and then deploy.

**Comment by gjost** [comment]
Yep it's in the latest `ddrpublic-master-5.3.0` package which is deployed on ddrstage.
