### ISSUE TITLE
ui: Add filters to browse results pages

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/ddr-public#182]
Currently, search results are filterable only on the main search results page (`https://ddr.densho.org/search/`). The object list pages for browsing by collection, facility and topic do not have this functionality. 

**For now, we should research and assess the required development time that will be required to implement.**

**Comment by gjost** [comment]
A first pass implementation is up on ddrstage:
- https://ddrstage.densho.org/browse/topics/
- https://ddrstage.densho.org/browse/facility/

Formatting is not perfect esp on facilities results but is functional.

**Comment by GeoffFroh** [comment]
Looks good on stage. @sarabeckman, @pkikawa and @GeoffFroh: please take a look and sign off

- [ ] @sarabeckman 
- [ ] @pkikawa 
- [ ] @GeoffFroh

**Comment by gjost** [comment]
Complete(?) as of `ddr-public` commit `f1aa958`, in package `ddrpublic-master_5.3.0`.
