### ISSUE TITLE
Add new Google Tag code

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/ddr-public#193]
Install Google Tag Manager code snippets to base templates

**Comment by GeoffFroh** [comment]
Implemented in 9cbca230ad4eb4c325a60432754196c723087c3b

**Comment by GeoffFroh** [comment]
@gjost: please merge to `master`, deploy, and then close this issue

**Comment by gjost** [comment]
Merged, pushed, pulled, restarted.
