### ISSUE TITLE
Interviews with multiple narrators not showing on Narrator page

### ISSUE THREAD

**Issue by sarabeckman** [denshoproject/ddr-public#210]
This bug was first noticed with this interview with 3 narrators: [Kay Uno Kaneko - Hana Shepard - Mae Matsuzaki Interview](https://ddr.densho.org/interviews/ddr-densho-1007-8-1/). The interview does not show up on the Narrator pages for [Kay Kaneko](https://ddr.densho.org/narrators/485/ )or [Hana Shepard](https://ddr.densho.org/narrators/838/) but does show up for [Mae Matsuzaki](https://ddr.densho.org/narrators/839/). 

The behavior is also seen with this interivew: [Terry Aratani - Fred Matsumura - Kenneth Okuma - Henry Bruno Yamada Interview](https://ddr.densho.org/interviews/ddr-densho-1000-3-1/). The interview does not appear on the Narrator pages for [Terry Aratani](https://ddr.densho.org/narrators/3/), [Kenneth Okuma](https://ddr.densho.org/narrators/5/), or [Fred Matsumura](https://ddr.densho.org/narrators/54/). The interview does show up for [Henry Bruno Yamada](https://ddr.densho.org/narrators/106/). 

I have checked the data for the interviews and the data is correct.

**Comment by gjost** [comment]
OMG this works...
> DOCSTORE.es.sql.query(body={'query': """SELECT id FROM ddrentity WHERE creators.id=838 AND creators.role='narrator'"""})

I wish I could replace all the `elasticsearch_dsl` code with SQL...

**Comment by gjost** [comment]
Existing code in `ddrpublic/ui/models/interviews` relied on a `narrator_id` field present in Interview `Entity` objects.  This field was an `int` and appropriate for singular narrators, not lists of narrators.

Found a solution (forthcoming) that involves modifying `ddrpublic/ui/models/interviews` and `elastictools.search.prepare` to search for interviews using `creator.id` and `creator.role`.

**Comment by gjost** [comment]
Fixed in commit `6c42031`, merged in to `master`, packaged, and installed in prod.
